version: 2.1
jobs:
  android:
    working_directory: ~/ci_cd_reactnative
    docker:
      - image: reactnativecommunity/react-native-android
    steps:
      - checkout
      - run: npx envinfo
      - run: yarn install
      # daemon mode has bug on circleCI
      # - run: cd android && chmod +x gradlew && ./gradlew --no-daemon bundleRelease assembleRelease

      # FASTLANE commands
      - run: gem install fastlane -NV
      - run: cd android && fastlane build_release_apk

      # Firebase commands
      - run:
          name: 'Install Firebase CLI'
          command: |
            curl -sL firebase.tools | bash
      # - run:
      #     command: fastlane add_plugin firebase_app_distribution
      - run: 'rvm install 2.2.5 && rvm use 2.2.5'
      - run:
          name: 'Deploy alpha build to Firebase'
          command: |
            bundle exec fastlane stage flavor:alpha branch:${CIRCLE_BRANCH} app_id:$FIREBASE_APP_ID_ALPHA firebase_token:$FIREBASE_TOKEN

      - run: cd android/app/build/outputs/apk/release && ls && pwd
      - store_artifacts:
          path: android/app/build/outputs/bundle/release
          destination: release-aab/
      - store_artifacts:
          path: android/app/build/outputs/apk/release
          destination: release-apk/

workflows:
  version: 2
  build_and_test:
    jobs:
      - android
