# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Builds the APK for release"
  lane :build_release_apk do
    gradle(task: "assembleRelease")
  end

  

  desc "Builds the AAB for release"
  lane :build_release_aab do
    gradle(task: "bundleRelease")
  end

  desc "Deploy to Firebase App Distribution"
  lane :deploy_firebase do
    release = firebase_app_distribution(
            build_release_apk,
            app: "#{env:app_id}",
            groups: "GA",
            release_notes: "Lots of amazing new features to test out!",
            apk_path: "android/app/build/outputs/apk/release/app-release.apk",
            firebase_cli_token: "#{env:firebase_token}"
        )
  end
end

